#!/usr/bin/env bash
_dev_completion() {
    if [ "${COMP_CWORD}" == "1" ]; then
        local commands=$(DEV_COMMANDS=1 dev)
        COMPREPLY=($(compgen -W "${commands}" -- "${COMP_WORDS[1]}"))
    else
        # Thanks to https://stackoverflow.com/a/14524311
        COMPREPLY=($(compgen -f  -- "${COMP_WORDS[$COMP_CWORD]}"))
    fi
}

complete -F _dev_completion dev
